#!/usr/bin/env python3
"""Generate 5 demo HTML files from templates."""

import os

BASE = "C:/claude_projects"

def px(id, size=800):
    return f"https://images.pexels.com/photos/{id}/pexels-photo-{id}.jpeg?auto=compress&cs=tinysrgb&w={size}"

def generate(template_path, data, out_path):
    with open(template_path, encoding="utf-8") as f:
        html = f.read()
    for k, v in data.items():
        html = html.replace("{{" + k + "}}", v)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"OK: {out_path}")

# =================== CAFE ===================
cafe_data = {
    "shop_name": "カフェ ブラン",
    "shop_name_en": "Café BLANC",
    "tagline": "丁寧に淹れた一杯と、手作りの焼き菓子を",
    "hero_image": px(35134952, 1600),
    "news1_date": "2025.03.10", "news1_text": "春の新メニュー「桜ラテ」が登場しました",
    "news2_date": "2025.02.14", "news2_text": "バレンタイン限定チョコレートケーキ好評販売中",
    "news3_date": "2025.01.06", "news3_text": "新年のご挨拶と1月の営業時間についてお知らせ",
    "menu_heading": "本日のメニュー",
    "menu1_name": "ドリップコーヒー", "menu1_image": px(13119734),
    "menu1_desc": "毎朝その日のために厳選した豆を手挽きで。余韻まで楽しめる一杯です。",
    "menu1_price": "¥650〜",
    "menu2_name": "季節のパティスリー", "menu2_image": px(31505379),
    "menu2_desc": "フランス仕込みのレシピで仕上げた、毎日変わる手作り焼き菓子です。",
    "menu2_price": "¥420〜",
    "menu3_name": "モーニングセット", "menu3_image": px(30403595),
    "menu3_desc": "トーストと旬のフルーツ、コーヒーまたは紅茶がセットになったモーニング。",
    "menu3_price": "¥980",
    "feature_heading": "カフェ ブランのこだわり",
    "feature1_icon": "☕", "feature1_title": "スペシャルティコーヒー",
    "feature1_desc": "産地直送の豆を毎週仕入れ、最高の状態で提供します。",
    "feature2_icon": "🥐", "feature2_title": "毎日手作りの焼き菓子",
    "feature2_desc": "防腐剤・添加物不使用。オーナーパティシエが毎朝焼き上げます。",
    "feature3_icon": "🌿", "feature3_title": "くつろぎの空間",
    "feature3_desc": "一人でも、大切な人と過ごすひとときにも。ゆったりとした時間をどうぞ。",
    "staff_image": px(3768914),
    "staff_title": "オーナー・パティシエ",
    "staff_name": "田中 美咲",
    "staff_bio": "フランス・リヨンにてパティスリーを学んだ後、都内カフェで5年のキャリアを積み独立。「日常の中に小さな幸せを」をテーマに、毎日丁寧に焼き菓子とコーヒーを提供しています。お客様が笑顔でお帰りになる瞬間が、いちばんの喜びです。",
    "voice1_text": "毎週末に通っています。コーヒーの香りと静かな空間がお気に入り。焼き菓子も種類が多くていつも迷ってしまいます。",
    "voice1_name": "K.T",
    "voice2_text": "モーニングの質が高くてコスパ最高。近所にこんなカフェがあって幸せです。スタッフさんも感じよくて居心地抜群。",
    "voice2_name": "M.S",
    "voice3_text": "手土産に焼き菓子を買って帰ることが多いです。友人にも好評で、プレゼントにも重宝しています。",
    "voice3_name": "A.Y",
    "address": "東京都渋谷区神南1-2-3 レジデンス渋谷 1F",
    "tel": "03-1234-5678",
    "hours": "8:00〜20:00（L.O. 19:30）",
    "closed": "不定休",
    "line_id": "cafeblanc",
}

generate(f"{BASE}/template_cafe.html", cafe_data, f"{BASE}/template_cafe_demo.html")

# =================== GYM ===================
gym_data = {
    "gym_name": "IRON WILL",
    "gym_name_en": "PERSONAL GYM SHIBUYA",
    "tagline": "変わる覚悟が、\n結果を変える。",
    "sub_tagline": "完全個室・完全マンツーマンのパーソナルジム。あなただけのプログラムで、理想のボディを手に入れる。",
    "hero_image": px(6389892, 1600),
    "stat1_num": "1,200+", "stat1_label": "累計会員数",
    "stat2_num": "98%", "stat2_label": "目標達成率",
    "stat3_num": "3ヶ月", "stat3_label": "平均変化期間",
    "stat4_num": "10年+", "stat4_label": "トレーナー経験",
    "program_heading": "プログラムラインアップ",
    "program1_name": "ダイエットコース", "program1_image": px(1229356),
    "program1_target": "FOR DIET",
    "program1_desc": "食事管理と有酸素・筋トレを組み合わせ、リバウンドしない体づくりをサポートします。",
    "program1_price": "¥44,000 / 月（週2回）",
    "program2_name": "ボディメイクコース", "program2_image": px(4761795),
    "program2_target": "FOR BODY",
    "program2_desc": "引き締まったスタイルを目指す方に。筋肉量を増やしながら理想のシルエットへ。",
    "program2_price": "¥44,000 / 月（週2回）",
    "program3_name": "アスリートコース", "program3_image": px(5262299),
    "program3_target": "FOR PERFORMANCE",
    "program3_desc": "競技力向上・怪我予防を目的とした専門的なトレーニングプログラムです。",
    "program3_price": "¥55,000 / 月（週2回）",
    "feature_heading": "IRON WILLが選ばれる理由",
    "feature1_num": "01", "feature1_title": "完全個室・プライベート空間",
    "feature1_desc": "他のお客様と顔を合わせることなく集中してトレーニングできます。",
    "feature2_num": "02", "feature2_title": "食事指導込みのプログラム",
    "feature2_desc": "トレーニングだけでなく毎日の食事もサポート。LINEで24時間相談可能。",
    "feature3_num": "03", "feature3_title": "全額返金保証",
    "feature3_desc": "3ヶ月コース終了時に満足いただけない場合は全額返金いたします。",
    "trainer_image": px(4164761),
    "trainer_title": "HEAD TRAINER",
    "trainer_name": "佐藤 健太",
    "trainer_bio": "NSCA認定パーソナルトレーナーとして10年以上のキャリア。元プロアスリートとしての経験を活かし、科学的根拠に基づいたトレーニング指導を行う。これまで1,000名以上の変身をサポート。",
    "trainer_cert1": "NSCA-CPT",
    "trainer_cert2": "JATI-ATI",
    "trainer_cert3": "栄養士",
    "flow1_title": "無料体験申込", "flow1_desc": "LINEまたはお電話でお申し込みください。当日のご予約も可能です。",
    "flow2_title": "カウンセリング", "flow2_desc": "現在の状態・目標・生活習慣をヒアリング。最適なプログラムをご提案します。",
    "flow3_title": "体験トレーニング", "flow3_desc": "実際にトレーナーと一緒にトレーニング。強度や方向性を確認します。",
    "flow4_title": "プログラム決定・入会", "flow4_desc": "ご納得いただけた場合はご入会手続きへ。無理な勧誘は一切ありません。",
    "flow5_title": "トレーニング開始", "flow5_desc": "専用アプリで進捗管理。毎回のセッション後にフィードバックをお渡しします。",
    "voice1_text": "3ヶ月で体重-8kg、体脂肪率-6%を達成。食事制限だけでなく筋肉もつけられて満足です。",
    "voice1_name": "Y.K", "voice1_result": "3ヶ月 -8kg",
    "voice2_text": "仕事が忙しくても続けられるよう柔軟にスケジュール調整してもらえます。トレーナーさんも熱心で心強い。",
    "voice2_name": "T.M", "voice2_result": "6ヶ月継続中",
    "voice3_text": "以前他のジムで挫折した経験があったので不安でしたが、ここなら続けられています。マンツーマンの安心感が違います。",
    "voice3_name": "A.H", "voice3_result": "4ヶ月 -6kg",
    "address": "東京都渋谷区道玄坂1-5-8 センタービル 3F",
    "tel": "03-2345-6789",
    "hours": "7:00〜23:00",
    "closed": "年中無休",
    "line_id": "ironwill_gym",
}

generate(f"{BASE}/template_gym.html", gym_data, f"{BASE}/template_gym_demo.html")

# =================== CHIRO ===================
chiro_data = {
    "shop_name": "渋谷はるの接骨院",
    "shop_subtitle": "骨格矯正・スポーツ整体・鍼灸",
    "tagline": "痛みのない毎日へ、\nていねいな施術で。",
    "sub_tagline": "骨格から根本的にアプローチ。通い続けるのではなく、通わなくていい体へ。",
    "hero_image": px(5215013, 1600),
    "news1_date": "2025.03.05", "news1_text": "4月より土曜日の受付時間を延長いたします（〜18:00）",
    "news2_date": "2025.02.01", "news2_text": "スポーツ外傷・オーバーユース障害の専門相談を開始しました",
    "news3_date": "2025.01.10", "news3_text": "2025年の診療スケジュールを更新しました",
    "treatment_heading": "施術メニュー",
    "treatment1_name": "骨盤矯正", "treatment1_image": px(6187638),
    "treatment1_desc": "産後の骨盤歪み・慢性的な腰痛・姿勢改善に。骨格の根本から整えます。",
    "treatment1_price": "¥5,500", "treatment1_time": "50分",
    "treatment2_name": "スポーツ整体", "treatment2_image": px(19641835),
    "treatment2_desc": "筋肉の張り・スポーツ障害・パフォーマンス向上に特化した施術です。",
    "treatment2_price": "¥6,600", "treatment2_time": "60分",
    "treatment3_name": "鍼灸治療", "treatment3_image": px(5722162),
    "treatment3_desc": "東洋医学のアプローチで自律神経・冷え・慢性疲労に効果的です。",
    "treatment3_price": "¥6,600", "treatment3_time": "60分",
    "feature_heading": "はるの接骨院が選ばれる理由",
    "feature1_icon": "🎓", "feature1_title": "国家資格保有者が施術",
    "feature1_desc": "柔道整復師・鍼灸師の国家資格保有者が全施術を担当します。",
    "feature2_icon": "🔍", "feature2_title": "初回60分の丁寧な問診",
    "feature2_desc": "生活習慣や動作パターンまで詳しくヒアリング。原因から探ります。",
    "feature3_icon": "🏠", "feature3_title": "完全予約制・プライベート空間",
    "feature3_desc": "待ち時間なし。他の患者様と顔を合わせない完全個室対応も可能。",
    "therapist_image": px(5765179),
    "therapist_title": "院長・柔道整復師・鍼灸師",
    "therapist_name": "山田 直樹",
    "therapist_bio": "整形外科・スポーツクリニックで7年のキャリアを積んだ後、地域密着の接骨院として独立。「症状を取り除くだけでなく、再発しない体づくり」をモットーに日々施術を行っています。",
    "therapist_cert1": "柔道整復師",
    "therapist_cert2": "鍼灸師",
    "flow1_title": "ご予約", "flow1_desc": "お電話またはLINEよりご予約ください。当日の急患も可能な限り対応します。",
    "flow2_title": "問診・検査", "flow2_desc": "初回は60分。生活習慣・症状・動きのクセを詳しく確認します。",
    "flow3_title": "施術方針のご説明", "flow3_desc": "原因と施術方針をわかりやすくご説明。ご納得いただいた上で進めます。",
    "flow4_title": "施術", "flow4_desc": "骨格・筋肉・神経にアプローチする丁寧な施術を行います。",
    "flow5_title": "アフターケア・次回予約", "flow5_desc": "セルフケア方法をお伝えし、必要に応じて次回のご予約をお取りします。",
    "voice1_text": "長年の腰痛が3回の施術でかなり改善しました。丁寧な説明で原因が分かって安心できました。",
    "voice1_name": "H.M", "voice1_age": "40代・男性",
    "voice2_text": "産後の骨盤矯正でお世話になっています。施術後の体の軽さが全然違います。子連れでも対応してもらえて助かります。",
    "voice2_name": "S.K", "voice2_age": "30代・女性",
    "voice3_text": "スポーツで痛めた膝の治療をしてもらいました。大会に間に合うよう調整してもらい感謝しています。",
    "voice3_name": "T.A", "voice3_age": "20代・男性",
    "address": "東京都渋谷区渋谷2-4-6 渋谷東ビル 1F",
    "tel": "03-3456-7890",
    "hours": "10:00〜20:00（最終受付 19:30）",
    "closed": "日曜・祝日",
    "line_id": "haruno_seikotsuin",
}

generate(f"{BASE}/template_chiro.html", chiro_data, f"{BASE}/template_chiro_demo.html")

# =================== NAIL ===================
nail_data = {
    "shop_name": "nail atelier miel",
    "shop_name_en": "nail atelier miel",
    "tagline": "爪先から、自分を好きになる。",
    "hero_image": px(3997390, 1600),
    "news1_date": "2025.03.01", "news1_text": "春のデザインカタログを更新しました",
    "news2_date": "2025.02.05", "news2_text": "ホワイトデー限定ネイルデザイン受付中",
    "news3_date": "2025.01.15", "news3_text": "3月の予約受付を開始しました（残りわずか）",
    "menu_heading": "メニュー",
    "menu1_name": "ジェルネイル", "menu1_image": px(5871831),
    "menu1_desc": "持ちが良く美しい仕上がり。豊富なカラーとデザインからお選びいただけます。",
    "menu1_price": "¥8,800〜", "menu1_time": "90分〜",
    "menu2_name": "ネイルアート", "menu2_image": px(6429663),
    "menu2_desc": "繊細なアートからトレンドデザインまで。お客様の「なりたいイメージ」を形に。",
    "menu2_price": "¥11,000〜", "menu2_time": "120分〜",
    "menu3_name": "ハンドケア", "menu3_image": px(3997384),
    "menu3_desc": "甘皮ケア・保湿・爪の形整えを丁寧に。素のままで美しい手元を目指します。",
    "menu3_price": "¥4,400", "menu3_time": "45分",
    "gallery1_image": px(5871831),
    "gallery2_image": px(6429663),
    "gallery3_image": px(3997384),
    "gallery4_image": px(3997390),
    "gallery5_image": px(4051843),
    "gallery6_image": px(4735139),
    "feature_heading": "nail atelier miel のこだわり",
    "feature1_icon": "💅", "feature1_title": "お客様一人ひとりに寄り添うデザイン",
    "feature1_desc": "ライフスタイルや職場環境に合わせた、「その人らしい」デザインをご提案します。",
    "feature2_icon": "✨", "feature2_title": "最高品質のジェル材料",
    "feature2_desc": "肌に優しく持ちが良い、国内外の高品質ジェルのみを使用しています。",
    "feature3_icon": "🛡️", "feature3_title": "徹底した衛生管理",
    "feature3_desc": "使い捨て用品の使用・器具の高圧滅菌処理で安心・清潔な環境を維持。",
    "artist_image": px(3998469),
    "artist_title": "オーナーネイリスト",
    "artist_name": "木村 さくら",
    "artist_bio": "ネイルスクール卒業後、都内有名サロンで5年間勤務。「お客様の爪の悩みに全力で向き合う」をモットーに独立。繊細なアートと丁寧なケアが好評で、多くのリピーターに恵まれています。",
    "artist_cert1": "JNECネイリスト技能検定1級",
    "artist_cert2": "ジェルネイル技能検定上級",
    "voice1_text": "繊細なアートが得意なサロンです。希望を伝えると想像以上のデザインに仕上げてくれます。絶対また来ます！",
    "voice1_name": "R.T",
    "voice2_text": "爪が薄くて他のサロンで断られた経験があったのですが、ここでは丁寧に対応してもらえました。本当に感謝です。",
    "voice2_name": "M.K",
    "voice3_text": "毎月通っています。施術中の会話も楽しくて、来るたびリフレッシュできます。ケアも丁寧で爪が健康になりました。",
    "voice3_name": "Y.O",
    "address": "東京都渋谷区神宮前3-7-2 プレミアビル 2F",
    "tel": "03-4567-8901",
    "hours": "10:00〜19:00（最終受付 18:00）",
    "closed": "月曜日",
    "line_id": "nail_miel",
    "instagram_id": "nail_atelier_miel",
}

generate(f"{BASE}/template_nail.html", nail_data, f"{BASE}/template_nail_demo.html")

# =================== REAL ESTATE ===================
re_data = {
    "company_name": "渋谷ホームズ",
    "company_name_en": "SHIBUYA HOMES REAL ESTATE",
    "tagline": "あなたの理想の住まいを、\n誠実に探し抜く。",
    "sub_tagline": "渋谷・代官山・恵比寿エリアを中心に、賃貸・売買物件を豊富にご用意。地域密着20年の実績で、あなたに最適な一室をご提案します。",
    "hero_image": px(6180674, 1600),
    "stat1_num": "5,000+", "stat1_label": "取扱物件数",
    "stat2_num": "20年", "stat2_label": "地域密着の実績",
    "stat3_num": "98%", "stat3_label": "顧客満足度",
    "stat4_num": "2,300+", "stat4_label": "成約実績",
    "news1_date": "2025.03.15", "news1_text": "渋谷区・恵比寿エリアに新規物件10件を追加しました",
    "news2_date": "2025.02.20", "news2_text": "春の引越しシーズンに向けたキャンペーンを開始しました",
    "news3_date": "2025.01.10", "news3_text": "2025年の営業時間・休業日についてのご案内",
    "property_heading": "おすすめ物件",
    "property1_name": "代官山ビューレジデンス", "property1_image": px(3316922),
    "property1_tag": "賃貸", "property1_area": "代官山", "property1_station": "代官山駅 徒歩3分",
    "property1_price": "¥220,000 / 月", "property1_detail": "2LDK / 68㎡ / 築3年",
    "property2_name": "渋谷プレミアムタワー", "property2_image": px(5997959),
    "property2_tag": "売買", "property2_area": "渋谷", "property2_station": "渋谷駅 徒歩5分",
    "property2_price": "¥9,800万円", "property2_detail": "3LDK / 82㎡ / 築7年",
    "property3_name": "恵比寿ガーデンテラス", "property3_image": px(13067890),
    "property3_tag": "賃貸", "property3_area": "恵比寿", "property3_station": "恵比寿駅 徒歩6分",
    "property3_price": "¥185,000 / 月", "property3_detail": "1LDK / 55㎡ / 築5年",
    "service_heading": "サービスラインアップ",
    "service1_icon": "🏠", "service1_name": "賃貸物件",
    "service1_desc": "渋谷・代官山・恵比寿エリアを中心に、単身〜ファミリー向けまで豊富なラインアップ。",
    "service2_icon": "🏢", "service2_name": "売買物件",
    "service2_desc": "マンション・一戸建て・土地。資産価値と住みやすさを兼ね備えた物件をご提案。",
    "service3_icon": "📊", "service3_name": "資産運用相談",
    "service3_desc": "投資用不動産・リノベーション相談など、資産形成のサポートも承ります。",
    "feature_heading": "渋谷ホームズが選ばれる理由",
    "feature1_num": "20年", "feature1_title": "地域密着の実績",
    "feature1_desc": "渋谷エリアに根ざして20年。地域の相場・特性を誰よりも熟知しています。",
    "feature2_num": "98%", "feature2_title": "高い顧客満足度",
    "feature2_desc": "ご成約後のアンケートで98%のお客様から「満足」の評価をいただいています。",
    "feature3_num": "無料", "feature3_title": "物件探しから手続きまで",
    "feature3_desc": "物件探し・内見・契約手続きのサポートはすべて無料。安心してお任せください。",
    "agent_image": px(3756679),
    "agent_title": "代表取締役・宅地建物取引士",
    "agent_name": "中村 誠一",
    "agent_bio": "20年以上、渋谷エリア一筋で不動産業に携わってきました。「お客様にとって本当に良い物件だけを提案する」という信念のもと、無理な営業は一切行いません。住まい選びに関するお悩みは何でもご相談ください。",
    "flow1_title": "お問い合わせ・ご相談", "flow1_desc": "電話・メール・ご来店にて受け付けております。まずはお気軽にどうぞ。",
    "flow2_title": "ヒアリング・物件のご提案", "flow2_desc": "ご希望の条件や予算をお聞きし、最適な物件をご提案します。",
    "flow3_title": "内見", "flow3_desc": "実際に物件をご覧いただきます。気になる点は何でもお聞きください。",
    "flow4_title": "お申し込み・審査", "flow4_desc": "ご希望の物件が決まりましたらお申し込みへ。各種手続きをサポートします。",
    "flow5_title": "ご契約・お引き渡し", "flow5_desc": "契約内容を丁寧にご説明。鍵のお引き渡しまで責任を持って対応します。",
    "voice1_text": "初めての一人暮らしで不安でしたが、こちらのスタッフさんが丁寧に説明してくれて安心できました。希望通りの物件に出会えて大満足です。",
    "voice1_name": "K.T",
    "voice2_text": "売却相談から実際の売却まで約2ヶ月でスムーズに完了しました。査定額も他社より高く、対応も誠実で信頼できました。",
    "voice2_name": "M.Y",
    "voice3_text": "転勤で急いで物件を探していたにも関わらず、希望条件に合った物件を3日で見つけてもらえました。対応の早さに感動しました。",
    "voice3_name": "S.H",
    "address": "東京都渋谷区渋谷1-8-5 渋谷ファーストビル 2F",
    "tel": "03-5678-9012",
    "hours": "10:00〜18:00",
    "closed": "日曜・祝日・水曜",
    "email": "info@shibuya-homes.jp",
    "license": "東京都知事（1）第XXXXX号",
}

generate(f"{BASE}/template_realestate.html", re_data, f"{BASE}/template_realestate_demo.html")

print("\nAll demos generated!")
